let camisetas = [
    {
        id: 0,
        nombreProducto: "Messi",
        precio: 20000,
        descipcion: "Lionel Andrés Messi Cuccittini, conocido como Leo Messi, es un futbolista argentino que juega como delantero",
        catergoria: "delantero",
        oferta: true,
    },
    {
        id: 1,
        nombreProducto: "Julian Alvarez",
        precio: 17000,
        descipcion: "Julián Álvarez es un futbolista argentino que juega como delantero en el Manchester City F. C. de la Premier League de Inglaterra.",
        catergoria: "delantero",
        oferta: true,
    },
    {
        id: 2,
        nombreProducto: "Di Maria",
        precio: 17000,
        descipcion: "Ángel Fabián Di María (Rosario, 14 de febrero de 1988) es un futbolista argentino. Juega de extremo en la Juventus de Turín de la Serie A de Italia.",
        catergoria: "delantero",
        oferta: false,
    },
    {
        id: 3,
        nombreProducto: "De Poul",
        precio: 15000,
        descipcion: "Rodrigo Javier de Paul Ferrarotti es un futbolista argentino, Formado y surgido en Racing Club, juega como centrocampista y su equipo actual es el Atlético de Madrid de la Primera División de España.",
        catergoria: "centrocampista",
        oferta: false,
    },
    {
        id: 4,
        nombreProducto: "Enzo Fernandez",
        precio: 15000,
        descipcion: "Enzo Jeremías Fernández es un futbolista argentino. Se desempeña como mediocampista y actualmente juega en el Benfica de la Primeira Liga de Portugal.",
        catergoria: "centrocampista",
        oferta: false,
    },
    {
        id: 5,
        nombreProducto: "Dybala",
        precio: 20000,
        descipcion: "Paulo Exequiel Dybala es un futbolista argentino. Se desempeña como delantero en la A. S. Roma de la Serie A de Italia",
        catergoria: "delantero",
        oferta: true,
    },
    {
        id: 6,
        nombreProducto: "Mac Allister",
        precio: 17000,
        descipcion: "Alexis Mac Allister es un futbolista argentino. Se desempeña como mediocampista ofensivo o volante mixto​ en el Brighton & Hove Albion de la Premier League de Inglaterra.",
        catergoria: "centrocampista",
        oferta: false,
    },
    {
        id: 7,
        nombreProducto: "Molina",
        precio: 12000,
        descipcion: "Nahuel Molina Lucero​, es un futbolista argentino que juega como defensor en el Atlético de Madrid de la Primera División de España.",
        catergoria: "defensa",
        oferta: false,
    },
    {
        id: 8,
        nombreProducto: "Acuña",
        precio: 15000,
        descipcion: "Marcos Javier Acuña es un futbolista profesional argentino que juega como lateral izquierdo en el club español Sevilla y en la selección argentina.",
        catergoria: "defensa",
        oferta: false,
    },
    {
        id: 9,
        nombreProducto: "Foyth",
        precio: 14000,
        descipcion: "Juan Marcos Foyth es un futbolista argentino que también posee la nacionalidad española. Juega como defensa y su equipo es el Villarreal C.F. de la Primera División de España.",
        catergoria: "defensa",
        oferta: false,
    },
    {
        id: 10,
        nombreProducto: "Tagliafico",
        precio: 17000,
        descipcion: "Nicolás Alejandro Tagliafico es un futbolista profesional argentino que juega como defensor en el Olympique de Lyon de la Ligue 1 de Francia y en la selección argentina",
        catergoria: "defensa",
        oferta: false,
    },
    {
        id: 11,
        nombreProducto: "Montiel",
        precio: 19000,
        descipcion: "Gonzalo Ariel Montiel es un futbolista argentino que juega como defensor en el Sevilla Fútbol Club de la Primera División de España.​ Además, es internacional con la selección argentina desde 2019.",
        catergoria: "defensa",
        oferta: false,
    },
    {
        id: 12,
        nombreProducto: "Pezzella",
        precio: 16000,
        descipcion: "Germán Alejo Pezzella es un futbolista argentino. Juega como defensa y milita en el Real Betis Balompié de la Primera División de España.​",
        catergoria: "defensa",
        oferta: false,
    },
    {
        id: 13,
        nombreProducto: "Armani",
        precio: 18000,
        descipcion: "arquero",
        catergoria: "Franco Armani es un futbolista argentino. Juega como arquero y su equipo actual es River Plate de la Primera División de Argentina. Es internacional con la selección Argentina desde 2018. Es el arquero argentino más ganador de la historia, con 22 títulos",
        oferta: false,
    },
    {
        id: 14,
        nombreProducto: "Otamendi",
        precio: 19000,
        descipcion: "Nicolás Hernán Gonzalo Otamendi es un futbolista argentino que juega como defensor​ y su actual equipo es el S. L. Benfica de la Primeira Liga de Portugal y para la selección argentina.",
        catergoria: "defensa",
        oferta: false,
    },
]

